# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RxSwiftPub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftPub
  pod 'RxCocoa', '~> 6.1.0'
  pod 'RxSwift', '~> 6.1.0'

end
