# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'RxSwiftPub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftPub
  
  # RxSwift基础库
  pod 'RxCocoa', '~> 6.1.0'
  pod 'RxSwift', '~> 6.1.0'

  #基于RxSwift的网络请求框架
  pod 'RxAlamofire', '~> 6.1.1'

  #自动布局库
  pod 'SnapKit', '~> 5.0.1'

end
