# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
flutter_application_path = '../fluttermodule'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'NativeOCTest' do
  install_all_flutter_pods(flutter_application_path)
  use_frameworks!
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
